# Sysbuild configuration file.

# Enable MCUboot using overwrite only mode for this sample.
SB_CONFIG_BOOTLOADER_MCUBOOT=y
# SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y
# SB_CONFIG_BOOT_MAX_IMG_SECTORS=512
# STEP 1.2 - Configure bootloader to use only one slot. 
SB_CONFIG_MCUBOOT_MODE_SINGLE_APP=y

